### ISSUE TITLE
Is the downloader still working?

### ISSUE THREAD

**Issue by PaulusElektrus** [omareldeeb/tum-moodle-downloader#11]
I am not sure whether I am to stupid or the tool is broken due to the new moodle system?

The courses can be found accurately, but no resources can be found nor they can be downloaded.

Eventually someone can tell me if the tool is still working?

Best Regards,
Paul :-)

**Comment by omareldeeb** [comment]
TUM Moodle seems to have changed quite a bit since this was last worked on. I'll look into getting it working again :)

**Comment by omareldeeb** [comment]
I've updated the HTML parsing, and listing and downloading resources should be working again now. Let me know if anything else comes up :)

**Comment by PaulusElektrus** [comment]
Thank you very much! I learned a lot from your work :-)
