### ISSUE TITLE
Download with config does not work. (python3 src/main.py download -h)

### ISSUE THREAD

**Issue by philipphirte** [omareldeeb/tum-moodle-downloader#13]
If I use the command  ``` python3 src/main.py download -h ```
(with the latest version of your software)

**it will force me into providing all these arguments:**
Download resources which match a 'file_pattern' from a 'course' into a 'destination' path. If parameters are omitted they are retrieved from 'src/course_config.json'

positional arguments:
  course        name of the course from which to download
  file_pattern  name pattern for the resources which are to be downloaded
  destination   path at which the download(s) should be stored
  
  With commit ID **8202c06** It uses the config.
  
  Would be amazing if someone could look into that.
  
  Maybe the command is just outdated....

**Comment by omareldeeb** [comment]
Hey Philipp, thanks for pointing this out! I've updated the parameters and made them explicit, i.e. instead of calling `download COURSE`, you'd call `download --course COURSE`, and not required so that omitting them properly retrieves them from the config files again.
